
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-rhpds-gitea
  namespace: gitea-operator
spec:
  sourceType: grpc
  image: quay.io/rhpds/gitea-catalog:v2.03
  displayName: Red Hat Demo Platform (Gitea)
  publisher: Red Hat Demo Platform

